server {
    listen 8080;
    listen [::]:8080;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Für eine Vite/SPA sinnvoll, damit Client-Routing funktioniert:
    location / {
        try_files $uri $uri/ /index.html;
    }
}